# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca2e2f89f6d9bfa0362a9ede6d44cee536a33ec5833bd9980f1e88bba4c3c666e5fd11ca3c2d4357428e6ba4ced4230aa87ddeb3738d09e875a69312047e91cf

test:
  secret_key_base: 64d8c47564def2507448ddd8b52457f0343167811cd547545f2211b232a5413ec2f44b6b34460e8a7843c000e3179b2059590b638d2348a055bc9c93b90fe9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
